GPT:
  API_KEY: "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"
  MODEL: "gpt-4-turbo"
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0

LLAMA:
  API_KEY: ""
  MODEL: "llama3.1-405b"
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0
